# Created using wingetcreate 1.6.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ITLDG.DocImageDownload
PackageVersion: 1.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: DocImageDownload.exe
  PortableCommandAlias: DocImageDownload
Installers:
- InstallerUrl: https://github.com/itldg/DocImageDownload/releases/download/v1.0.0/DocImageDownload.zip
  Architecture: x64
  InstallerSha256: BDD62DE674E59D4A1DA920785B131E9FCE4A8305D3E68B9508976B74E8A07A30
ManifestType: installer
ManifestVersion: 1.6.0
